
services:
  open-webui:
    build: 
      dockerfile_inline: | 
        FROM ghcr.io/open-webui/open-webui:main
        RUN mkdir  /app/backend/data/shared_files
    #    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3000:8080"
    volumes:
      - open-webui:/app/backend/data
      - ./shared_files:/app/backend/data/shared_files
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    environment:
      #https://docs.openwebui.com/getting-started/logging
      - GLOBAL_LOG_LEVEL=DEBUG
  mitmproxy:
    image: mitmproxy/mitmproxy
    container_name: mitmproxy
    ports:
      - "9091:9091"
    command: mitmweb --listen-host 0.0.0.0 --listen-port 8081 --web-port 9091 --web-host 0.0.0.0 --mode reverse:https://api.openai.com

volumes:
  open-webui:
